# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [185]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [186]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [187]:
df_apps = pd.read_csv('apps.csv')

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [188]:
df_apps.describe()

        Rating       Reviews  Size_MBs
count 9,367.00     10,841.00 10,841.00
mean      4.19    444,111.93     19.77
std       0.52  2,927,628.66     21.40
min       1.00          0.00      0.01
25%       4.00         38.00      4.90
50%       4.30      2,094.00     11.00
75%       4.50     54,768.00     27.00
max       5.00 78,158,306.00    100.00

In [189]:
df_apps.shape

(10841, 12)

In [190]:
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti YardÄ±m Toplama,SOCIAL,NaN,0,8.70,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.00,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.50,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.00,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.00,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up

In [191]:
df_apps.sample(5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
9346,App vault,TOOLS,3.40,25094,3.40,"10,000,000",Free,0,Everyone,Tools,"July 18, 2018",Varies with device
1895,PriorityONE Credit Union of Fl,FINANCE,4.70,178,12.00,"1,000",Free,0,Everyone,Finance,"June 12, 2018",5.0 and up
4878,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.40,1518,37.00,"100,000",Free,0,Everyone,Art & Design,"August 3, 2018",2.3 and up
5974,Plastic Surgery Surgeon Simulator Er Doctor Games,FAMILY,3.70,3482,37.00,"500,000",Free,0,Everyone,Casual,"August 7, 2018",4.4 and up
4174,GALAK-Z: Variant Mobile,GAME,3.90,145,79.00,"10,000",Free,0,Everyone,Action,"July 30, 2018",4.4 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [192]:
df_apps.drop(labels=['Last_Updated', 'Android_Ver'], axis=1, inplace=True)

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [193]:
rows_with_na = df_apps.Rating[df_apps.Rating.isna() == True].index
rows_with_na

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            5428, 5500, 5574, 5813, 5814, 5840, 5862, 6141, 7035, 7175],
           dtype='int64', length=1474)

In [194]:
rows_with_na.size

1474

In [195]:
df_apps_clean = df_apps.dropna()
df_apps_clean.shape

(9367, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [196]:
df_duplicates_app = df_apps_clean[df_apps_clean.App.duplicated() == True]

In [197]:
df_duplicates_app[df_duplicates_app.App == "Instagram"]

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10808,Instagram,SOCIAL,4.50,66577446,5.30,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.50,66509917,5.30,"1,000,000,000",Free,0,Teen,Social

In [198]:
df_apps_clean = df_apps_clean.drop_duplicates(subset=['App', 'Type', 'Price'])
df_apps_clean.shape

(8199, 10)

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [199]:
df = df_apps_clean

In [200]:
df.sort_values(by=['Rating', 'Reviews'], ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2095,RÃ­os de Fe,LIFESTYLE,5.00,141,15.00,"1,000",Free,0,Everyone,Lifestyle
2438,"FD Calculator (EMI, SIP, RD & Loan Eligilibility)",FINANCE,5.00,104,2.30,"1,000",Free,0,Everyone,Finance
3115,OraciÃ³n CX,LIFESTYLE,5.00,103,3.80,"5,000",Free,0,Everyone,Lifestyle
2107,Barisal University App-BU Face,FAMILY,5.00,100,10.00,"1,000",Free,0,Everyone,Education
2069,Master E.K,FAMILY,5.00,90,19.00,"1,000",Free,0,Everyone,Education
...,...,...,...,...,...,...,...,...,...,...
728,Truck Driving Test Class 3 BC,FAMILY,1.00,1,2.00,50,Paid,$1.49,Everyone,Education
1208,Thistletown CI,PRODUCTIVITY,1.00,1,6.60,100,Free,0,Everyone,Productivity
1271,MbH BM,MEDICAL,1.00,1,2.30,100,Free,0,Everyone,Medical
1314,CR Magazine,BUSINESS,1.00,1,7.80,100,Free,0,Everyone,Business
2416,BJ Bridge Standard American 2018,GAME,1.00,1,4.90,"1,000",Free,0,Everyone,Card

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [201]:
df.sort_values(by=['Size_MBs'], ascending=False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
9942,Talking Babsy Baby: Baby Games,LIFESTYLE,4.00,140995,100.00,"10,000,000",Free,0,Everyone,Lifestyle;Pretend Play
10687,Hungry Shark Evolution,GAME,4.50,6074334,100.00,"100,000,000",Free,0,Teen,Arcade
9943,Miami crime simulator,GAME,4.00,254518,100.00,"10,000,000",Free,0,Mature 17+,Action
9944,Gangster Town: Vice District,FAMILY,4.30,65146,100.00,"10,000,000",Free,0,Mature 17+,Simulation
3144,Vi Trainer,HEALTH_AND_FITNESS,3.60,124,100.00,"5,000",Free,0,Everyone,Health & Fitness
...,...,...,...,...,...,...,...,...,...,...
2648,Ad Remove Plugin for App2SD,PRODUCTIVITY,4.10,66,0.02,"1,000",Paid,$1.29,Everyone,Productivity
5798,ExDialer PRO Key,COMMUNICATION,4.50,5474,0.02,"100,000",Paid,$3.99,Everyone,Communication
2684,My baby firework (Remove ad),FAMILY,4.10,30,0.01,"1,000",Paid,$0.99,Everyone,Entertainment
7966,Market Update Helper,LIBRARIES_AND_DEMO,4.10,20145,0.01,"1,000,000",Free,0,Everyone,Libraries & Demo
4696,Essential Resources,LIBRARIES_AND_DEMO,4.60,237,0.01,"50,000",Free,0,Everyone,Libraries & Demo

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [202]:
df.sort_values(by=['Reviews'], ascending=False).head(50)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4.10,78158306,5.30,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4.40,69119316,3.50,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4.50,66577313,5.30,"1,000,000,000",Free,0,Teen,Social
10784,Messenger â Text and Video Chat for Free,COMMUNICATION,4.00,56642847,3.50,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,4.60,44891723,98.00,"100,000,000",Free,0,Everyone 10+,Strategy
10744,Clean Master- Space Cleaner & Antivirus,TOOLS,4.70,42916526,3.40,"500,000,000",Free,0,Everyone,Tools
10835,Subway Surfers,GAME,4.50,27722264,76.00,"1,000,000,000",Free,0,Everyone 10+,Arcade
10828,YouTube,VIDEO_PLAYERS,4.30,25655305,4.65,"1,000,000,000",Free,0,Teen,Video Players & Editors
10746,"Security Master - Antivirus, VPN, AppLock, Boo...",TOOLS,4.70,24900999,3.40,"500,000,000",Free,0,Everyone,Tools
10584,Clash Royale,GAME,4.60,23133508,97.00,"100,000,000",Free,0,Everyone 10+,Strategy
10763,Candy Crush Saga,GAME,4.40,22426677,74.00,"500,000,000",Free,0,Everyone,Casual
10770,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.50,17712922,40.00,"500,000,000",Free,0,Teen,Communication
10735,Snapchat,SOCIAL,4.00,17014787,5.30,"500,000,000",Free,0,Teen,Social
10489,"360 Security - Free Antivirus, Booster, Cleaner",TOOLS,4.60,16771865,3.40,"100,000,000",Free,0,Everyone,Tools
10731,My Talking Tom,GAME,4.50,14891223,36.00,"500,000,000",Free,0,Everyone,Casual
10594,8 Ball Pool,GAME,4.50,14198297,52.00,"100,000,000",Free,0,Everyone,Sports
10302,DU Battery Saver - Battery Charger & Battery Life,TOOLS,4.50,13479633,14.00,"100,000,000",Free,0,Everyone,Tools
10354,BBM - Free Calls & Messages,COMMUNICATION,4.30,12842860,3.50,"100,000,000",Free,0,Everyone,Communication
10549,Cache Cleaner-DU Speed Booster (booster & clea...,TOOLS,4.50,12759663,15.00,"100,000,000",Free,0,Everyone,Tools
10757,Twitter,NEWS_AND_MAGAZINES,4.30,11667403,6.30,"500,000,000",Free,0,Mature 17+,News & Magazines
10721,Viber Messenger,COMMUNICATION,4.30,11334799,3.50,"500,000,000",Free,0,Everyone,Communication
10578,Shadow Fight 2,GAME,4.60,10979062,88.00,"100,000,000",Free,0,Everyone 10+,Action
10813,Google Photos,PHOTOGRAPHY,4.50,10858556,6.90,"1,000,000,000",Free,0,Everyone,Photography
10724,LINE: Free Calls & Messages,COMMUNICATION,4.20,10790289,3.50,"500,000,000",Free,0,Everyone,Communication
10717,Pou,GAME,4.30,10485308,24.00,"500,000,000",Free,0,Everyone,Casual
10792,Skype - free IM & video calls,COMMUNICATION,4.10,10484169,3.50,"1,000,000,000",Free,0,Everyone,Communication
10628,PokÃ©mon GO,GAME,4.10,10424925,85.00,"100,000,000",Free,0,Everyone,Adventure
10388,Minion Rush: Despicable Me Official Game,GAME,4.50,10216538,36.00,"100,000,000",Free,0,Everyone 10+,Casual;Action & Adventure
10694,Yes day,GAME,4.50,10055521,94.00,"100,000,000",Free,0,Everyone,Casual
10695,Hay Day,FAMILY,4.50,10053186,94.00,"100,000,000",Free,0,Everyone,Casual
10644,Dream League Soccer 2018,GAME,4.60,9882639,74.00,"100,000,000",Free,0,Everyone,Sports
10696,My Talking Angela,GAME,4.50,9881829,99.00,"100,000,000",Free,0,Everyone,Casual
10660,VivaVideo - Video Editor & Photo Movie,VIDEO_PLAYERS,4.60,9879473,40.00,"100,000,000",Free,0,Teen,Video Players & Editors
10786,Google Chrome: Fast & Secure,COMMUNICATION,4.30,9642995,3.50,"1,000,000,000",Free,0,Everyone,Communication
10817,Maps - Navigate & Explore,TRAVEL_AND_LOCAL,4.30,9235155,12.00,"1,000,000,000",Free,0,Everyone,Travel & Local
10672,Hill Climb Racing,GAME,4.40,8923587,63.00,"100,000,000",Free,0,Everyone,Racing
10734,Facebook Lite,SOCIAL,4.30,8606259,5.30,"500,000,000",Free,0,Teen,Social
10649,Asphalt 8: Airborne,GAME,4.50,8389714,92.00,"100,000,000",Free,0,Teen,Racing
10699,Mobile Legends: Bang Bang,GAME,4.40,8219586,99.00,"100,000,000",Free,0,Teen,Action
10322,Battery Doctor-Battery Life Saver & Battery Co...,TOOLS,4.50,8190074,17.00,"100,000,000",Free,0,Everyone,Tools
10396,Piano Tiles 2â¢,GAME,4.70,8118880,36.00,"100,000,000",Free,0,Everyone,Arcade
10777,Temple Run 2,GAME,4.30,8118609,62.00,"500,000,000",Free,0,Everyone,Action
10822,Google,TOOLS,4.40,8033493,3.40,"1,000,000,000",Free,0,Everyone,Tools
10359,"Truecaller: Caller ID, SMS spam blocking & Dialer",COMMUNICATION,4.50,7820209,3.50,"100,000,000",Free,0,Everyone,Communication
10711,SHAREit - Transfer & Share,TOOLS,4.60,7790693,17.00,"500,000,000",Free,0,Everyone,Tools
10389,Sniper 3D Gun Shooter: Free Shooting Games - FPS,GAME,4.60,7671249,36.00,"100,000,000",Free,0,Mature 17+,Action
10676,Farm Heroes Saga,GAME,4.40,7614130,70.00,"100,000,000",Free,0,Everyone,Casual
10576,PicsArt Photo Studio: Collage Maker & Pic Editor,PHOTOGRAPHY,4.50,7594559,34.00,"100,000,000",Free,0,Teen,Photography
10461,"PhotoGrid: Video & Pic Collage Maker, Photo Ed...",PHOTOGRAPHY,4.60,7529865,6.90,"100,000,000",Free,0,Everyone,Photography
10502,GO Launcher - 3D parallax Themes & HD Wallpapers,PERSONALIZATION,4.50,7464996,6.15,"100,000,000",Free,0,Everyone,Personalization

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [203]:
ratings=df.Content_Rating.value_counts()
ratings

Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: Content_Rating, dtype: int64

In [204]:
fig = px.pie(df, names='Content_Rating')

In [205]:
fig.show(renderer='browser')

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [206]:
df.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,$1.49,Everyone,Arcade
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,$0.99,Everyone,Arcade
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0,Everyone,Medical

In [207]:
df.describe()

        Rating       Reviews  Size_MBs
count 8,199.00      8,199.00  8,199.00
mean      4.17    255,072.97     20.09
std       0.54  1,985,241.40     21.65
min       1.00          1.00      0.01
25%       4.00        126.00      4.90
50%       4.30      2,992.00     11.00
75%       4.50     43,612.50     28.00
max       5.00 78,158,306.00    100.00

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   object
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 704.6+ KB

Problem with comma character in Installs

In [209]:
df.Installs = df.Installs.astype(str).str.replace(',',"")
df.Installs = pd.to_numeric(df.Installs)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   object
 1   Category        8199 non-null   object
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   int64
 6   Type            8199 non-null   object
 7   Price           8199 non-null   object
 8   Content_Rating  8199 non-null   object
 9   Genres          8199 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 704.6+ KB

In [210]:
df[['Installs', 'App']].groupby(['Installs']).count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [211]:
df.Price.head()

21        0
28    $1.49
47    $0.99
82        0
99        0
Name: Price, dtype: object

In [212]:
df.Price = df.Price.astype(str).str.replace('$', "")
df.Price = pd.to_numeric(df.Price)

/tmp/ipykernel_2335567/2055282529.py:1: FutureWarning:

The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

### The most expensive apps sub $250

In [213]:
df.sort_values(by=['Price'], ascending=False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3946,I'm Rich - Trump Edition,LIFESTYLE,3.60,275,7.30,10000,Paid,400.00,Everyone,Lifestyle
2461,I AM RICH PRO PLUS,FINANCE,4.00,36,41.00,1000,Paid,399.99,Everyone,Finance
4606,I Am Rich Premium,FINANCE,4.10,1867,4.70,50000,Paid,399.99,Everyone,Finance
3145,I am rich(premium),FINANCE,3.50,472,0.94,5000,Paid,399.99,Everyone,Finance
3554,ð I'm rich,LIFESTYLE,3.80,718,26.00,10000,Paid,399.99,Everyone,Lifestyle
5765,I am rich,LIFESTYLE,3.80,3547,1.80,100000,Paid,399.99,Everyone,Lifestyle
1946,I am rich (Most expensive app),FINANCE,4.10,129,2.70,1000,Paid,399.99,Teen,Finance
2775,I Am Rich Pro,FAMILY,4.40,201,2.70,5000,Paid,399.99,Everyone,Entertainment
3221,I am Rich Plus,FAMILY,4.00,856,8.70,10000,Paid,399.99,Everyone,Entertainment
3114,I am Rich,FINANCE,4.30,180,3.80,5000,Paid,399.99,Everyone,Finance
1331,most expensive app (H),FAMILY,4.30,6,1.50,100,Paid,399.99,Everyone,Entertainment
2394,I am Rich!,FINANCE,3.80,93,22.00,1000,Paid,399.99,Everyone,Finance
3897,I Am Rich,FAMILY,3.60,217,4.90,10000,Paid,389.99,Everyone,Entertainment
2193,I am extremely Rich,LIFESTYLE,2.90,41,2.90,1000,Paid,379.99,Everyone,Lifestyle
3856,I am rich VIP,LIFESTYLE,3.80,411,2.60,10000,Paid,299.99,Everyone,Lifestyle
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
4264,Golfshot Plus: Golf GPS,SPORTS,4.10,3387,25.00,50000,Paid,29.99,Everyone,Sports

Remove all apps that cost more than $250

In [214]:
df = df[df.Price < 250]
df.sort_values(by=['Price'], ascending=False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2281,Vargo Anesthesia Mega App,MEDICAL,4.60,92,32.00,1000,Paid,79.99,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4.00,6,1.30,100,Paid,39.99,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4.20,134,1.80,1000,Paid,37.99,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,3.50,214,68.00,1000,Paid,33.99,Everyone,Medical
2463,PTA Content Master,MEDICAL,4.20,64,41.00,1000,Paid,29.99,Everyone,Medical
2207,EMT PASS,MEDICAL,3.40,51,2.40,1000,Paid,29.99,Everyone,Medical
4264,Golfshot Plus: Golf GPS,SPORTS,4.10,3387,25.00,50000,Paid,29.99,Everyone,Sports
504,AP Art History Flashcards,FAMILY,5.00,1,96.00,10,Paid,29.99,Mature 17+,Education
4772,Human Anatomy Atlas 2018: Complete 3D Human Body,MEDICAL,4.50,2921,25.00,100000,Paid,24.99,Everyone,Medical
3241,"Muscle Premium - Human Anatomy, Kinesiology, B...",MEDICAL,4.20,168,25.00,10000,Paid,24.99,Everyone,Medical
2119,NewTek NDI,PHOTOGRAPHY,3.50,77,1.20,1000,Paid,19.99,Everyone,Photography
4470,DRAGON QUEST VIII,FAMILY,4.50,7812,27.00,50000,Paid,19.99,Everyone 10+,Role Playing
2293,Hospitalist Handbook,MEDICAL,4.80,12,18.00,1000,Paid,19.99,Everyone,Medical
526,USMLE Step 2 CK Flashcards,FAMILY,5.00,1,40.00,10,Paid,19.99,Everyone,Education
2473,boattheory.ch Full 2018,FAMILY,4.70,54,50.00,1000,Paid,19.40,Everyone,Education
4090,I am Rich Premium Plus,FINANCE,4.60,459,2.00,10000,Paid,18.99,Everyone,Finance
1508,SkyTest BU/GU Lite,BUSINESS,2.90,28,20.00,500,Paid,17.99,Everyone,Business
3778,The World Ends With You,GAME,4.60,4108,13.00,10000,Paid,17.99,Everyone 10+,Arcade
2603,2017 EMRA Antibiotic Guide,MEDICAL,4.40,12,3.80,1000,Paid,16.99,Everyone,Medical
3439,Trine 2: Complete Story,GAME,3.80,252,11.00,10000,Paid,16.99,Teen,Action

### Highest Grossing Paid Apps (ballpark estimate)

In [215]:
df['Revenue'] = df.Installs.mul(df.Price)
df.sort_values(by=['Revenue'], ascending=False)

/tmp/ipykernel_2335567/520152923.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue
9220,Minecraft,FAMILY,4.50,2376564,19.00,10000000,Paid,6.99,Everyone 10+,Arcade;Action & Adventure,"69,900,000.00"
8825,Hitman Sniper,GAME,4.60,408292,29.00,10000000,Paid,0.99,Mature 17+,Action,"9,900,000.00"
7151,Grand Theft Auto: San Andreas,GAME,4.40,348962,26.00,1000000,Paid,6.99,Mature 17+,Action,"6,990,000.00"
7477,Facetune - For Free,PHOTOGRAPHY,4.40,49553,48.00,1000000,Paid,5.99,Everyone,Photography,"5,990,000.00"
7977,Sleep as Android Unlock,LIFESTYLE,4.50,23966,0.85,1000000,Paid,5.99,Everyone,Lifestyle,"5,990,000.00"
...,...,...,...,...,...,...,...,...,...,...,...
4508,myAirâ¢ for Air10â¢ by ResMed,MEDICAL,3.70,236,18.00,50000,Free,0.00,Everyone,Medical,0.00
4507,AK Math Coach,FAMILY,3.60,283,18.00,50000,Free,0.00,Everyone,Education,0.00
4506,Forgotten Hill: Fall,GAME,4.40,1063,18.00,50000,Free,0.00,Teen,Adventure,0.00
4505,AE Video Poker,GAME,4.00,721,18.00,50000,Free,0.00,Teen,Casino,0.00
10835,Subway Surfers,GAME,4.50,27722264,76.00,1000000000,Free,0.00,Everyone 10+,Arcade,0.00

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [216]:
df.Category.nunique()

33

In [217]:
top10_category=df.Category.value_counts()[:10]

In [218]:
bar = px.bar(x = top10_category.index, y=top10_category.values)

In [219]:
bar.show(renderer='browser')

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [220]:
category_vs_installs=df[['Category', 'Installs']].groupby('Category').sum()
# category_vs_installs=df.groupby('Category').agg({'Installs': pd.Series.sum}) # Same as above
category_vs_installs=category_vs_installs.sort_values(by=['Installs'], ascending=False)[:10]
category_vs_installs.head()

                  Installs
Category
GAME           13858762717
COMMUNICATION  11039241530
TOOLS           8099724500
PRODUCTIVITY    5788070180
SOCIAL          5487841475

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [221]:
h_bar = px.bar(x = category_vs_installs.Installs, y = category_vs_installs.index, orientation='h')
h_bar.update_layout(xaxis_title='Number of downloads', yaxis_title='Category')
h_bar.show(renderer='browser')

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [222]:
df_app_installs = df[['App', 'Installs', 'Category']].groupby('Category').agg({'App': pd.Series.count, 'Installs': pd.Series.sum})
df_app_installs = df_app_installs.sort_values(by=['Installs', 'App'], ascending=False)
df_app_installs.head(10)

                     App     Installs
Category
GAME                 910  13858762717
COMMUNICATION        257  11039241530
TOOLS                719   8099724500
PRODUCTIVITY         301   5788070180
SOCIAL               203   5487841475
PHOTOGRAPHY          263   4649143130
FAMILY              1606   4437554490
VIDEO_PLAYERS        148   3916897200
TRAVEL_AND_LOCAL     187   2894859300
NEWS_AND_MAGAZINES   204   2369110650

In [223]:
scatter = px.scatter(df_app_installs, x='App', y='Installs', title='Category Concentration', size='App', hover_name=df_app_installs.index, color='Installs')
scatter.update_layout(xaxis_title='Number of Apps (Lower = More Concentrated)', yaxis_title='Installs', yaxis=dict(type='log'))
scatter.show(renderer='browser')

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [224]:
df.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue
21,KBA-EZ Health Guide,MEDICAL,5.00,4,25.00,1,Free,0.00,Everyone,Medical,0.00
28,Ra Ga Ba,GAME,5.00,2,20.00,1,Paid,1.49,Everyone,Arcade,1.49
47,Mu.F.O.,GAME,5.00,2,16.00,1,Paid,0.99,Everyone,Arcade,0.99
82,Brick Breaker BR,GAME,5.00,7,19.00,5,Free,0.00,Everyone,Arcade,0.00
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5.00,1,4.60,5,Free,0.00,Everyone,Medical,0.00

In [225]:
df.Genres.value_counts()

Tools                                718
Entertainment                        467
Education                            429
Productivity                         301
Personalization                      298
                                    ...
Adventure;Brain Games                  1
Travel & Local;Action & Adventure      1
Art & Design;Pretend Play              1
Music & Audio;Music & Video            1
Lifestyle;Pretend Play                 1
Name: Genres, Length: 114, dtype: int64

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

In [230]:
stack=df.Genres.str.split(';', expand=True).stack()
num_genres = stack.value_counts()
num_genres

Tools                      719
Education                  587
Entertainment              498
Action                     304
Productivity               301
Personalization            298
Lifestyle                  298
Finance                    296
Medical                    292
Sports                     270
Photography                263
Business                   262
Communication              258
Health & Fitness           245
Casual                     216
News & Magazines           204
Social                     203
Simulation                 200
Travel & Local             187
Arcade                     185
Shopping                   180
Books & Reference          171
Video Players & Editors    150
Dating                     134
Puzzle                     124
Maps & Navigation          118
Role Playing               111
Racing                     103
Action & Adventure          96
Strategy                    95
Food & Drink                94
Educational                 93
Adventure                   78
Auto & Vehicles             73
Weather                     72
Pretend Play                68
Brain Games                 65
Libraries & Demo            64
Art & Design                62
House & Home                62
Board                       57
Comics                      54
Parenting                   50
Card                        46
Events                      45
Beauty                      42
Casino                      37
Music & Video               31
Creativity                  31
Trivia                      28
Word                        22
Music                       21
Music & Audio                1
dtype: int64

In [233]:
bar = px.bar(x = num_genres.index[:15], # index = category name
                 y = num_genres.values[:15], # count
                 title='Top Genres',
                 hover_name=num_genres.index[:15],
                 color=num_genres.values[:15],
                 color_continuous_scale='Agsunset')
     
bar.update_layout(xaxis_title='Genre',
yaxis_title='Number of Apps',
coloraxis_showscale=False)
     
bar.show(renderer='browser')

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [234]:
df_free_vs_paid = df.groupby(["Category", "Type"], as_index=False).agg({'App': pd.Series.count})
df_free_vs_paid.head()

            Category  Type  App
0     ART_AND_DESIGN  Free   58
1     ART_AND_DESIGN  Paid    3
2  AUTO_AND_VEHICLES  Free   72
3  AUTO_AND_VEHICLES  Paid    1
4             BEAUTY  Free   42

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

In [236]:
g_bar = px.bar(df_free_vs_paid,
                   x='Category',
                   y='App',
                   title='Free vs Paid Apps by Category',
                   color='Type',
                   barmode='group')
     
g_bar.update_layout(xaxis_title='Category',
                        yaxis_title='Number of Apps',
                        xaxis={'categoryorder':'total descending'},
                        yaxis=dict(type='log'))
     
g_bar.show(renderer='browser')

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

In [243]:
box = px.box(df_apps_clean,
                 y='Installs',
                 x='Type',
                 color='Type',
                 notched=True,
                 points='all',
                 title='How Many Downloads are Paid Apps Giving Up?')
     
box.update_layout(yaxis=dict(type='log'))
     
box.show(renderer='browser')

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [247]:
df_paid_apps = df[df['Type'] == 'Paid']

box = px.box(df_paid_apps, 
                 x='Category', 
                 y='Revenue',
                 title='How Much Can Paid Apps Earn?')
     
box.update_layout(xaxis_title='Category',
                      yaxis_title='Paid App Ballpark Revenue',
                      xaxis={'categoryorder':'min ascending'},
                      yaxis=dict(type='log'))
     
     
box.show(renderer='browser')

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [248]:
box = px.box(df_paid_apps,
                 x='Category',
                 y="Price",
                 title='Price per Category')
     
box.update_layout(xaxis_title='Category',
                      yaxis_title='Paid App Price',
                      xaxis={'categoryorder':'max descending'},
                      yaxis=dict(type='log'))
     
box.show(renderer='browser')

In this lesson we looked at how to:

    Pull a random sample from a DataFrame using .sample()

    How to find duplicate entries with .duplicated() and .drop_duplicates()

    How to convert string and object data types into numbers with .to_numeric()

    How to use plotly to generate beautiful pie, donut, and bar charts as well as box and scatter plots


You can download the completed code for today in this lesson.


Well done on completing today's lessons! ððð I hope you enjoyed todayâs Google Play Store analysis. It's incredible how much more of a clear picture we can get about the app ecosystem just by looking into some scraped website data for the Google Play Store.